### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by timdrysdale** [dpreid/pidcontroller#6]
In line with github convention, let's change branch `master` to `main` on this project, as we have been meaning to do this for a while. I tried doing it on a fork but that way I cannot trigger a PR, so better for owner to do it on the upstream repo (this one). See this [procedure from github](https://github.com/github/renaming). I've tried renaming the master to main, and back again, on the fork, and had no issues.

**Comment by dpreid** [comment]
New main branch created and set to default.
